// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using two_realities.Data;

#nullable disable

namespace two_realities.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("two_realities.Models.FavoritePair", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleTwo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearOne")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearTwo")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("FavoritePairs");
                });

            modelBuilder.Entity("two_realities.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
